name: Update readme with blog posts
on: 
  push:
    branches: [ main ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://rlevchenko.com/rss/
          max: 3
          readme-section: feed
          branch: main
          empty-commits: false
          template: "#### [{{ title }}]({{ link }}) \n*{{ pubDate }}*\n\n"