name: Update this repo's README

#on:
#  schedule:
    # Once a day at 8 AM
#    - cron: 0 8 * * *
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://github.com/sep7ic/sep7ic.github.io/commits/main.atom
          readme-section: feed